# Shell variables
# Generated by 'wal'
wallpaper='/home/gibranlp/Pictures/wallPapers/wallhaven-2kdqjm.jpg'

# Special
background='#051828'
foreground='#d2dddc'
cursor='#d2dddc'

# Colors
color0='#051828'
color1='#24605A'
color2='#28675C'
color3='#2E7162'
color4='#59906B'
color5='#678F8E'
color6='#98B4B4'
color7='#d2dddc'
color8='#939a9a'
color9='#24605A'
color10='#28675C'
color11='#2E7162'
color12='#59906B'
color13='#678F8E'
color14='#98B4B4'
color15='#d2dddc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
