--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gibranlp/Pictures/wallPapers/wallhaven-2kdqjm.jpg"

-- Special
background="#051828"
foreground="#d2dddc"
cursor="#d2dddc"

-- Colors
color0="#051828"
color1="#24605A"
color2="#28675C"
color3="#2E7162"
color4="#59906B"
color5="#678F8E"
color6="#98B4B4"
color7="#d2dddc"
color8="#939a9a"
color9="#24605A"
color10="#28675C"
color11="#2E7162"
color12="#59906B"
color13="#678F8E"
color14="#98B4B4"
color15="#d2dddc"
