--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gibranlp/Pictures/Wallpapers/wall.jpg"

-- Special
background="#171213"
foreground="#a7c3c6"
cursor="#a7c3c6"

-- Colors
color0="#171213"
color1="#2A5F66"
color2="#526261"
color3="#A17647"
color4="#3C926A"
color5="#38708E"
color6="#23BCB7"
color7="#a7c3c6"
color8="#74888a"
color9="#2A5F66"
color10="#526261"
color11="#A17647"
color12="#3C926A"
color13="#38708E"
color14="#23BCB7"
color15="#a7c3c6"
