# Shell variables
# Generated by 'wal'
wallpaper='/home/gibranlp/Pictures/Wallpapers/wall.jpg'

# Special
background='#171213'
foreground='#a7c3c6'
cursor='#a7c3c6'

# Colors
color0='#171213'
color1='#2A5F66'
color2='#526261'
color3='#A17647'
color4='#3C926A'
color5='#38708E'
color6='#23BCB7'
color7='#a7c3c6'
color8='#74888a'
color9='#2A5F66'
color10='#526261'
color11='#A17647'
color12='#3C926A'
color13='#38708E'
color14='#23BCB7'
color15='#a7c3c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
