#!/usr/bin/env bash
#                                    
#   _____  _____  _____  _____  _      
# |     ||  _  || __  ||   __|| | ___ 
# |  |  ||     ||    -||__   || || . |
# |__  _||__|__||__|__||_____||_||  _|
#    |__|                        |_|  
# QARSlp Qtile Auto-Ricing System
# by: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
rofi_command="rofi -theme ~/.config/rofi/left_toolbar.rasi"

# Options
full="100%"
auto="Auto"


options="$full\n$auto"

chosen="$(echo -e "$options" | $rofi_command -p '  Fan Control' -dmenu -selected-row 0)"
case $chosen in
    $full)
		sleep 1; nbfc set -f 0 -s 100
		;;
    $auto)
		sleep 1; nbfc set -f 0 -a
		;;
esac



