#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
pkill dunst &
pywalfox update &
picom --backend glx &
cp ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc &
cp ~/.cache/wal/colors.Xresources ~/.Xresources &
oomox-cli -o oomox-wal ~/.cache/wal/colors-oomox &
dunst &
wal -R 