#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
#

picom --config ~/.config/picom/picom.conf &
pywalfox update &
#killall dunst &
numlockx on &
owncloud &
caffeine &
kdeconnect-indicator &
blueman-applet &
wal -R -q &

