#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
#
dir="$HOME/Pictures/wallPapers/"
file=`/bin/ls -1 "$dir" | sort --random-sort | head -1` # Select random file on directory
path=`readlink --canonicalize "$dir/$file"` # Converts to full path
#### Set Wallpaper Selected / Random
while getopts "w:t:lr" opt; do
  case "$opt" in
    w) wall=$OPTARG ;;
    t) back=$OPTARG ;;
    l) light="-L" ;;
    r) path="`cat "${HOME}"/.config/qtile/current_wallpaper`"
  esac
done
theme="--backend $back"

set_wall(){
  if [ -z "$wall" ]
    then
      echo "${path}" | tee ~/.config/qtile/current_wallpaper #Write wallpaper path to file
      wpg -s ${path} ${theme} ${light} # Wal sets wallpaper and genates new color scheme
      sudo rm -rf /usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/src/img/wallpapers/background.jpg
      sudo cp "${path}" /usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/src/img/wallpapers/background.jpg #Copy background image image to be used in lightdm
      qtile cmd-obj -o cmd -f restart # Restarts Qtile
    else
      echo "${wall}" | tee ~/.config/qtile/current_wallpaper #Write wallpaper path to file
      wpg -s ${wall} ${theme} ${light} # Wal sets wallpaper and genates new color scheme
      sudo cp "${wall}" /usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/src/img/wallpapers/background.jpg #Copy background image image to be used in lightdm
      qtile cmd-obj -o cmd -f restart 
  fi
}
set_wall