#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
function i_files(){
\cp -r ~/QARSlp/dotfiles/.[^.]* ~/ 
sudo \cp -r ~/QARSlp/dotfiles/.[^.]* /root 
sudo \cp -r  ~/QARSlp/scripts/* ~/.local/bin/ 
sudo chmod +x ~/.local/bin/*
sudo \cp -r ~/QARSlp/lightdm/* /etc/lightdm
sudo \cp -r ~/QARSlp/lightdm-webkit /usr/share
sudo \cp ~/QARSlp/installer/etc/X11/xorg.conf.d/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf
sudo cp ~/QARSlp/fonts/otf/* /usr/share/fonts/OTF/
sudo cp ~/QARSlp/fonts/ttf/* /usr/share/fonts/TTF/
}

i_files
